data_config: {
  'glove_pretrain_yelp': '/data/dataset/word2vec',
  'glove_pretrain_amazon': '/data/dataset/word2vec',
  '2015': {
    raw: 'data/raw/2015',
    processed: 'data/processed/2015',
    output: 'data/output/2015',
  },
  '2016': {
    raw: 'data/raw/2016',
    processed: 'data/processed/2016',
    output: 'data/output/2016',
  }
}